import os
import sys
import importlib
import shutil
import random
from zlapi.models import Message, MultiMsgStyle, MessageStyle

des = {
    'version': "1.2.0",
    'credits': "ngbao",
    'description': "Load toàn bộ lệnh hiện có.",
    'power': "Admin"
}


# 🔹 Lưu toàn bộ lệnh đã load
LOADED_COMMANDS = {}

def clean_pycache(path):
    """🧹 Xoá cache __pycache__"""
    for root, dirs, _ in os.walk(path):
        for d in dirs:
            if d == "__pycache__":
                try:
                    shutil.rmtree(os.path.join(root, d))
                    print(f"[CMDLOAD] 🧹 Đã xoá cache: {os.path.join(root, d)}")
                except Exception as e:
                    print(f"[CMDLOAD] ⚠️ Không thể xoá cache {d}: {e}")

def ensure_init_files(path):
    """🧩 Tự tạo file __init__.py trong tất cả thư mục"""
    for root, dirs, _ in os.walk(path):
        for d in dirs:
            init_file = os.path.join(root, d, "__init__.py")
            if not os.path.exists(init_file):
                with open(init_file, "w", encoding="utf-8") as f:
                    f.write("# Auto-generated by cmdload\n")

def handle_cmdload_command(message, message_object, thread_id, thread_type, author_id, client):
    try:
        # 🧭 Xác định thư mục modules
        base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../"))
        modules_dir = os.path.join(base_dir)
        os.makedirs(modules_dir, exist_ok=True)

        # Ép Python hiểu đúng package
        if base_dir not in sys.path:
            sys.path.append(base_dir)
        if os.path.dirname(base_dir) not in sys.path:
            sys.path.append(os.path.dirname(base_dir))

        clean_pycache(modules_dir)
        ensure_init_files(modules_dir)

        loaded_modules = []
        loaded_count = 0
        error_modules = []

        possible_funcs = ["TQuan", "PTA", "get_mitaizl", "get_command", "get_commands"]

        print(f"[CMDLOAD] 🔍 Đang quét thư mục: {modules_dir}")

        for root, dirs, files in os.walk(modules_dir):
            for file in files:
                if not file.endswith(".py") or file.startswith("__"):
                    continue

                rel_path = os.path.relpath(os.path.join(root, file), os.path.dirname(base_dir))
                module_name = rel_path.replace(os.sep, ".").replace(".py", "")

                try:
                    # Reload module
                    if module_name in sys.modules:
                        module = importlib.reload(sys.modules[module_name])
                    else:
                        module = importlib.import_module(module_name)

                    found_command = False
                    for func_name in possible_funcs:
                        if hasattr(module, func_name):
                            func = getattr(module, func_name)
                            if callable(func):
                                commands = func()
                                if isinstance(commands, dict):
                                    LOADED_COMMANDS.update(commands)
                                    loaded_count += len(commands)
                                    loaded_modules.append(f"{module_name}.{func_name}()")
                                    found_command = True
                    if not found_command:
                        print(f"[CMDLOAD] ⚠️ {module_name} không có hàm lệnh hợp lệ.")

                except Exception as e:
                    error_modules.append(f"{module_name} → {e}")
                    print(f"[CMDLOAD] ❌ Lỗi khi load {module_name}: {e}")

        # 🧠 Tên người thực thi
        author_name = "Không xác định"
        try:
            user_info = client.fetchUserInfo(author_id)
            if user_info and hasattr(user_info, "changed_profiles"):
                author_name = user_info.changed_profiles.get(str(author_id), {}).get("zaloName", "Không xác định")
        except Exception:
            pass

        # 📋 Nội dung tin nhắn
        msg = (
            f"{author_name}\n"
            f"✅ Đã load thành công {loaded_count} lệnh\n"
            f"📦 Tổng số module có lệnh: {len(loaded_modules)}\n"
        )

        if loaded_modules:
            msg += "\n\n🔹 Module đã load:\n"
            msg += "\n".join(f"• {m}" for m in loaded_modules[:50])
            if len(loaded_modules) > 50:
                msg += f"\n... (và {len(loaded_modules) - 50} module khác)"
        if error_modules:
            msg += f"\n\n❌ {len(error_modules)} module lỗi khi load!"

        # 🎨 Style highlight tên
        styles = MultiMsgStyle([
            MessageStyle(offset=0, length=len(author_name), style="color", color="#db342e", auto_format=False),
            MessageStyle(offset=0, length=len(author_name), style="bold", auto_format=False)
        ])

        # ✉️ Gửi tin nhắn có TTL tự xoá
        client.replyMessage(
            Message(text=msg, style=styles),
            message_object,
            thread_id=thread_id,
            thread_type=thread_type,
            ttl=180000
        )

        # 💥 Reaction ngẫu nhiên
        for icon in random.sample(["⚡", "🔥", "💥", "🚀", "🧠", "💫", "✨", "🔧", "✅", "💎"], 5):
            try:
                client.sendReaction(message_object, icon, thread_id, thread_type)
            except Exception:
                pass

        print(f"[CMDLOAD] ✅ Hoàn tất load {loaded_count} lệnh từ {len(loaded_modules)} module.")

    except Exception as e:
        client.replyMessage(
            Message(text=f"❌ Lỗi khi cmdload: {e}"),
            message_object,
            thread_id=thread_id,
            thread_type=thread_type,
            ttl=12000
        )
        print(f"[CMDLOAD] ❌ Lỗi tổng thể: {e}")


def PTA():
    return {
        "load": handle_cmdload_command
    }
